# Generated by Django 5.2.8 on 2025-11-18 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Request_app', '0002_maintenancerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenancerequest',
            name='category',
            field=models.CharField(choices=[('ELECTRICAL', 'Electrical'), ('PLUMBING', 'Plumbing'), ('HVAC', 'HVAC'), ('IT', 'IT'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROCESS', 'In Process'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
